#!/bin/sh 

VERSION=v56 

#*******************************************************************************
# Lancement du programme de prétraitement PRAIRIE
#
#@author  S. Loyer
# 
#*******************************************************************************
# remplacement vieux Bourne Shell sous Solaris < 11
#SL if [ -z "$RANDOM" ]; then
#SL 		[ -x /bin/ksh ] && exec ksh $0 "$@" || exec bash $0 "$@"
#SL fi


nom_script=${0##*/}

# ********************************************************************
# fonction i_want_random : $RANDOM est pas posix alors on utilise shuf
# ********************************************************************
i_want_random() { 
	# genere 1 aleatoire de 6 chiffres
	shuf -n 1 -i 0-999999 |awk '{printf("%6.6d",$1)}'
}
#*******************************************************************************
# Fonction : affiche l'usage
#*******************************************************************************
print_usage() {
    echo "  * Usage : ${nom_script} [ options ] fich1 fich2 fich3  ...      ( version courante : $VERSION )"
	echo "   fich1 fich2 ...        : fichiers RNX2 ou RNX3, une ou plusieurs stations ( d.Z .o .rnx .crx.gz ) chemin relatif ou absolu"
    echo "                            pour infos sur formats et noms, cf. ${GS_DATABASE}/prairie/RINEX_303.pdf" 
    echo "   [ -force_unique ]      : ne traite que la premiere station detectee (cas des melanges rnx2/rnx3, e.g. usn9 et USN9"
	echo "   [ -aide ]              : affiche aide detaillee"
	echo "   [ -aide_options ]      : affiche ensemble des options du fichier option "
	echo "   [ -pas pas ]           : en secondes (e.g 0.1 / 30.): specifie le pas des donnees en sortie (0=toutes)"
	echo "   [ -ignore GREC ]       : codes (rinex) permettant de specifier les obs. ignorees a la lecture"
	echo "                             E=GALILEO G=GPS R=GLONASS C=COMPASS exemple : -ignore RG (ou GR) = garde uniquement GALILEO "
	echo "   [ -options ficopt ]    : avec chemin complet si specifie cf. option [-aide_options]"
	echo "                            Si non specifie depend du nom des fichiers rinex traites"
	echo "   [ -historik HISTORIK ] : avec chemin complet  : nom du fichier historik glonass (defaut) " 
 	echo "                            e.g. ${GS_DATABASE}/constell/historik_glonass (defaut)"
 	echo "  * ENTREES DES BIAIS     "
	echo "   [ -cc2noncc fichp1p2 ] : passe la correction cc2noncc avec fichier fichp1p2 (defaut = non)"
 	echo "                            note: a partir de v40 cette correction est faite dans prairie "
	echo "   [ -wsb FICHIERMUSAT ]  : avec chemin complet  : nom du fichier WSB "
 	echo "   [ -osb FICHIEROSB ]    : avec chemin complet : nom du fichier OSB (format SINEX BIAS)"
 	echo "                            -osb remplace -wsb (soit l'un soit les autres) "
	echo "   [ -optimal ]           : ajoute les options pour un traitement classique CC2NONCC + GPS (WL) + GLONASS "
	echo "   [ -no_historik ]       : supprime l'attache du fichier historik (pour associer [ -optimal -no_historik ] )"
 	echo "  * SORTIES PRINCIPALES:  "
	echo "   [ -path path ]         : repertoire de retour des pretraitements "  
	echo "   [ -f ]                 : force ecriture du fichier de sortie"
	echo "   [ -out ficout ]        : nom du fichier retour des donnees (dans path) " 
	echo "   [ -listing ficlis ]    : nom du fichier listing de prairie (dans path) " 
	echo "   [ -sort ]              : trie le fichier de mesures en sortie en fonction de la date (defaut = non)"
	echo "   [ -nopdgr ]            : supprime la sortie du fichier de mesures (cas des etudes WL pour eviter gros fichier)"
 	echo "  * SORTIES DIVERSES:     "
	echo "   [ -sor_wsb fic]        : nom eventuel du fichier de retour (dans path) du fichier SORTIE_MUSAT ( NONE => pas de retour)"
	echo "   [ -sor_p1c1 fic]       : nom eventuel du fichier de retour (dans path) du fichier BIAISMOYENS_WL_P1C1.dat ( NONE => pas de retour) "
	echo "   [ -sor_speciale fic]   : nom eventuel du fichier de retour (dans path) du fichier SPECIALE.dat  ( NONE => pas de retour) "
	echo "   [ -submit ]            : (specif. CNES) soumission linux3 avec attente de retour job (sinon interactif). "
	echo "                            si on ne veut pas attendre: lancer en batch" 
	echo "   [ -lT cputime ]        : (specif. CNES) temps reserve pour les jobs individuels soumis (sinon automatique) "
	echo "   [ -lM mem ]            : (specif. CNES) memoire reserve en megaoctets pour les jobs individuels soumis (defaut = $taille_mem) "
	echo ""
	echo "  * ENTREES ANNEXES"
	echo "   [ -v VERSION ]         : utilise la version specifiee (VERSION sous la forme \"vnn\" pour v34 et superieures) version defaut = $VERSION"
	echo "   [ -selection SELECTION ]: avec chemin complet : nom du fichier selection_obs a utiliser (sinon le defaut est utilise)" 
	echo "   [ -orb XXX ]: ajoute autom. les orbites parmis ${KNOWN_SP3_CODE} et calcule les elev/azim si les coord. stations dans l entete RNX "
	echo "                             si position entete inconnue, calcule la trajectoire et determine type mobile/statique. cf. aussi [-statique |-mobile]"
	echo "                             si option \"SCINTILLATION nn\" alors l'elev. nn sert de masque pour les scintillations"
	echo "   [ -orb XXX -repertoire_orb dir ] : recherche les orbites sp3 de la forme xxxwwwwd.sp3 ou xxxwwwwd.sp3.Z dans le repertoire dir (uniquement pour tests)"
	echo "   [ -orb nom_sp3_1 -orb nom_sp3_2 ... ] : prend les orbites fournies / incompatible avec ci dessus"
	echo "   [ -orbex orbex  ]       : fichier orbex pour calcul de l'attitude gzippe ou non  [ -orbex orbex.gz  ]  " 
	echo "   [ -meta(data) ficmeta ] : fichier metadata (defaut = $METADATA)" 
    echo "   [ -antex ficantex ]     : attache le fic. antex et applique les corrections PCO/PCV après la lecture (uniquement si -orb présent)" 
    echo "                                            si orbex absent  : calcul PCO radial uniquement"
    echo "                                            si orbex present : calcul PCO avec attitude + PCV" 
    echo "   [ -sinex sinex.snx ]    : fichier sinex comme source des coords station, antenne et rotation" 
 	echo "   [ -statique |-mobile ]  : si -orb present force le mode de calcul de la position/trajectoire (defaut = inconnu) " 
    echo "   [ -elevmin cutoff ]     : si -orb present supprime les données en dessous de cutoff (en degré) (v47)"
    echo "                             les données ou l'elev n'a pas pu etre calculee sont eliminees"
    echo "   [ -elevmin_keep_unkn cutoff ] : idem ci dessus mais les données ou l'elev n'a pas pu etre calculee sont gardées (v48)"
	echo "   [ -masque MASQUE ]      : si -orb present supprime les donnees hors du masque apres la lecture " 
    echo "                             notes : - les donnees sans info d elev/azim sont eliminees"
    echo "                                     - l'effet est cumule avec ELEVMIN"
	echo "                                     - si -orb est absent cette option (et ELEVMIN) sont ignorees."
	echo "                                     - exemple de fichier masque sous ${GS_DATABASE}/prairie/exemple_masque_5_10.txt"
	echo "   [ -eclipse sec ]        : suppression des données entre deb_ecl et fin_ecl + sec (sec > 0 ) "
	echo "                             ( ne fonctionne qu'avec [ -orb ] )" 
	echo "   [ -eclipse_bord sec ]   : idem -eclipse mais seules les donnees des eclipses à moins d'1H de 0H/24H sont supprimees"
    echo "   [ -freqs FF]            : selection les lignes concernant les freqs FF dans le fichier selection e.g -freqs 15 "
	echo "   [ -no_posit ]           : supprime le calcul de point meme si -orb (si on veut seulement [-eclipse], donc)"
    echo "   [ -acq_only ]           : stoppe prairie apres l'acquisition des donnees (affiche les statistiques) "
	echo "   [ -attitude ficatt ]    : attache le fichier d attitude ficatt"  
	echo "   [ -debug ]              : copie le repertoire de travail dans path/DEBUGPRAI"
	echo "   [ -raboule ]            : copie le  fichier selection type (defaut) sous le nom selection_observables.dat "
	echo ""
	echo "  * exemple1: ${nom_script}  -f  -options ${GS_DATABASE}/prairie/options_GPS.dat"
	echo "                         -cc2noncc ${GS_DATABASE}/prairie/p1c1bias.2000p "
	echo "                         -wsb ${GS_DATABASE}/prairie/WSBREF.res.dat "
	echo "                         -out SORTIE.ESS *d.Z"
	echo ""
	echo "  * exemple2: ${nom_script}  -f  *d.Z -orb GRG -options ${GS_DATABASE}/prairie/options_scintillation10.dat"
	echo ""
	return
}

print_options() {

cat  "${GS_DATABASE}/prairie/options.txt" 

return 
}
#*******************************************************************************
#                                                                              *
#                        D E B U T    D U    S C R I P T                       *
#                                                                              *
#*******************************************************************************

temps_cpu=0 # automatique si non specifie
taille_mem=2000 # automatique si non specifie
pas=0.
QSUB='. '
path_init=$PWD 
path=$PWD
ATTITUDE='NUL'
fichier_option='NUL'
FICHIERMUSAT='NUL'
FICHIEROSB='NUL'
HISTORIK=${GS_DATABASE}/constell/historik_glonass # defaut 
METADATA=${GS_DATABASE}/prairie/igs_satellite_metadata.snx # defaut 
ANTEX='NUL'  # defaut
P1P2='NUL' 
SINEX='NUL' 
liste_fic=''
outlis='NUL' 
outPDG='sortiePDGR90'
outmusat='SORTIE_MUSAT' 
outp1c1='BIAISMOYENS_WL_P1C1.dat'
outspeciale='SPECIALE.dat'
unset out1  
out2="out.prairie.dat" 
n=0 
force=0 
QS=0 
SORT=0
force_unique=0 
COPIE_SELECTION_DEFAUT='NON'
debugtout=0 
type_orb='NUL'
f_orb_list=""
MASQUE='NUL' 
mode_position='NUL'
cutoff_elev='NUL'
repertoire_orb='NUL' 
debug_wl='0' 
ACQ_ONLY='0' 
sec_ecl='NUL' 
posit_demande='NUL'
garde_elev='0'
ECLBORD='NUL'
ORBEX='NUL' 
FREQUENCES='NUL' 
MODIF_SELECTION=0 
DO_NOT_OUTPDGR=0 
KNOWN_SP3_CODE="G20 GRG MG3 GRM" 
echo 

defaut="  * DEFAUT (si aucun autre argument que les fichiers rinex): exe_prairie -pas $pas -v $VERSION -out sortiePDGR90 -path \$PWD "

OUTILS_GPS=${GS_HOME}/scripts/outils_GPS

CC2NONCC=${OUTILS_GPS}/cc2noncc 
DECOMP_HATANAKA=${OUTILS_GPS}/CRZ2RNX
SELECTION_OBS_DEFAUT=${GS_DATABASE}/prairie/selection_observables.dat
ROOT_SP3=${GS_DATABASE}/orbites/SP3
ROOT_SP3_LOC="/work/GRGS/users/gnsexp"
SAUTS_DE_TUCS=${GS_DATABASE}/pole/liste_sauts_tucs_1s.dat


if [ $# -eq 0 ] ; then 
	print_usage
	printf "%s\n\n" "$defaut"
	exit 
fi

commande=$*

while [ $# -gt 0 ] ; do
  case $1 in  
  -acq_only)
     ACQ_ONLY="1"
     shift  
     ;;         
  -aide)
     print_usage
 	 printf "%s\n\n" "$defaut"
     prairie_info 
     exit 0
     ;;
  -aide_options)
     print_options     
     exit 0
     ;;
  -antex) 
     shift 
     ANTEX=$1
     shift
     ;;
  -attitude) 
     shift 
     ATTITUDE=$1
     shift
     ;;    
  -eclipse_bord)
     shift
     sec_ecl=$1 
     ECLBORD="1"
     shift
     ;; 
  -eclipse)
     shift
     sec_ecl=$1 
     shift
     ;; 
  -orb)
      shift
      # deux cas :
      # ca existe: incremente la liste des fichiers sp3
      if [ -s $1 ] ; then
  	    f_orb_list="${f_orb_list} ${1}" 
  	  # sinon suppose type sp3 automatique (GRG/G20,XXX,etc...)
      else
        type_orb=${1}
      fi 
     shift 
     ;;
  -repertoire_orb) 
     shift
     repertoire_orb=$1
     shift 
     ;;
  -statique) 
     mode_position='FORCE_STATIQUE'
     shift 
     ;;     
  -mobile)
     mode_position='FORCE_MOBILE'  
     shift 
     ;;      
  -no_posit)
     posit_demande='0'
     shift 
     ;;      
  -elevmin_keep_unkn) 
     shift 
     cutoff_elev=$1
     garde_elev='1'
     shift 
     ;; 
  -elevmin) 
     shift 
     cutoff_elev=$1
     shift 
     ;; 
  -freqs)
     shift 
     FREQUENCES="$1"
     MODIF_SELECTION=1 
     shift
     ;;
  -meta*)
     shift 
     METADATA=$1 
     shift 
     ;;  
  -path) 
     shift 
     path=$1 
     shift
     ;; 
  -pas) 
     shift 
     pas=$1 
     shift 
     ;; 
  -orbex)
     shift 
     ORBEX=$1 
     shift 
     ;; 
  -v)
     shift 
     VERSION=$1 
     shift 
     ;;  
  -wsb)
     shift 
     FICHIERMUSAT=$1 
     shift 
     ;;  
  -osb)
     shift 
     FICHIEROSB=$1 
     shift 
     ;;  
  -historik)
     shift 
     HISTORIK=$1 
     shift 
     ;;
  -no_historik)
     HISTORIK='NUL'
     shift 
     ;;
  -optimal)
     P1P2=${GS_DATABASE}/prairie/p1c1bias.2000p
     FICHIERMUSAT=${GS_DATABASE}/prairie/WSBREF.res.dat
     HISTORIK=${GS_DATABASE}/constell/historik_glonass
     SELECTION_OBS=${SELECTION_OBS_DEFAUT} 
     shift
     ;; 
  -options)
     shift 
     fichier_option=$1 
     shift 
     ;;  
  -selection)
     shift 
     SELECTION_OBS=$1 
     shift 
     ;;  
  -sinex) 
     shift 
     SINEX=$1
     shift
     ;;
  -raboule)
     COPIE_SELECTION_DEFAUT='OUI'
     shift 
     ;;  
  -out)
     shift
     outPDG=$1
     shift 
     ;;
  -f)
     shift 
     force=1
     ;;
  -sort)
     shift 
     SORT=1
     ;;
  -cc2noncc) 
     shift  
     P1P2=$1 
     shift
     ;;  
  -listing)
     shift 
     outlis=$1 
     shift
     ;; 
  -submit)
     # module ne sert a rien 08/09/2014 on met chemin qsub en dur ! 
     # QSUB='/opt/pbs/default/bin/qsub -W umask=0027 -W block=true'
     # QSUB='/opt/pbs/default/bin/qsub -q batch@10.120.42.2 -W umask=0027 '
     QSUB='/opt/pbs/default/bin/qsub -q batch@10.120.42.1 -W umask=0027 '
     QS=1
     shift 
     ;;
   -sor_wsb)
     shift   
     outmusat=$1
     shift
     ;;
   -sor_p1c1)
     shift   
     outp1c1=$1
     shift
     ;;
   -sor_speciale)
     shift   
     outspeciale=$1
     shift
     ;;
   -lT)
     shift   
     temps_cpu=$1
     shift
     ;; 
   -lM)
     shift
     taille_mem=$1
     shift
     ;;
   -ignore)
     shift   
     CONS_IGNORE=$1
     liste_cons_ignorees=$(echo "${CONS_IGNORE}" | sed -e "s/\(.\)/\1 /g") 
     MODIF_SELECTION=1    
     shift
     ;;
   -masque)
     shift   
     MASQUE=$1
     shift
     ;;       
   -debug_wl)
     debug_wl='1'  
     shift 
     ;; 
   -debug)
     # copie le repertoire de travail dans path/DEBUG_PRAI 
     debugtout='1' &&  debug_wl='1'
     # echo $debugtout 
     shift
     ;;  
   -force_unique) 
     force_unique=1 
     shift      
     ;;  
   -nopdgr)
     DO_NOT_OUTPDGR=1
     shift
     ;;
   *) 
  if [ -s "$1" ] && [ -f "$1" ] ; then 
    liste_fic=${liste_fic}" "$(readlink -f "$1")  
    n=$(echo ${n}+1 | bc) 
    if [  -z "${out1}" ] ; then 
      out1=$(basename "$1")
    fi 
    out2=$(basename "$1")".out.prai"
  else 
    echo "fichier $1 absent ou option $1 inconnue "
  fi 
  shift
  ;; 
  esac
done 
# 
# fonction de test des fichiers et affichage erreur/plantage sinon
test_exit_file () {
	fic_exist="$1" 
	mess_err="$2" 
	if [ -s "${fic_exist}" ] && [ -f "${fic_exist}" ] ; then 
  	  return 0
  	else 
  	  echo "ERR: ${mess_err}"
  	  exit 1
    fi  
}

# Variables environnement + programmes selon machine 
OUTILS_GPS=${GS_HOME}/scripts/outils_GPS

CC2NONCC=${OUTILS_GPS}/cc2noncc 
DECOMP_HATANAKA=${OUTILS_GPS}/CRZ2RNX
PRAIRIELNX=prairie.$VERSION.lnx              ; # dans bin/OS donc dans le PATH
SELECTION_OBS_DEFAUT=${GS_DATABASE}/prairie/selection_observables.dat


# valeur par defaut si unset
if [ -z "${SELECTION_OBS}" ] ; then 
  SELECTION_OBS=${SELECTION_OBS_DEFAUT} 
fi 

# option raboule
if [ "${COPIE_SELECTION_DEFAUT}" = "OUI" ] ; then
  cp -p "${SELECTION_OBS_DEFAUT}" ./selection_observables.dat
  echo " -> $(ls -l ./selection_observables.dat)"
  exit 0
fi 

# numero version 
if [ "${VERSION}" = "dev" ] ; then 
  VERSION_NUMBER="00" 
else 
  VERSION_NUMBER=${VERSION##v}
fi

if [ ! -d "${path}" ] ; then
  echo " Return path ${path} doesn't exist   "
  exit 
fi  

if [ -s "${path}/${outPDG}" ] ; then 
  case $force in 
  1)
   echo " Warning: File ${path}/${outPDG} overwritten (-f)   "
   \rm "${path}/${outPDG}"
  ;;
  0) 
   echo "ERR: File ${path}/${outPDG} already exist  : stop (use -f to force overwriting of output file) "
   exit 
  ;; 
  esac 
fi
#   
if [ ! -x "$(which ${PRAIRIELNX})" ] ; then 
   echo " Unable to access executable file ${PRAIRIELNX} (major problem !)"
   exit 
fi
# ce fichier est recquis a partir de la v40   
test_exit_file "${SELECTION_OBS}"  "Unable to access ${SELECTION_OBS}: After v40 the file selection_obs is requested"

if [  "${fichier_option}" != "NUL" ] ; then 
  test_exit_file "${fichier_option}" "Unable to access file option file ${fichier_option}  (give complete path)"
fi 
if [ "${FICHIERMUSAT}" != "NUL" ] ; then
  test_exit_file "${FICHIERMUSAT}" "Unable to access file  biais (WL) file ${FICHIERMUSAT} (give complete path)"
fi 
if [ "${FICHIEROSB}" != "NUL" ] ; then
  test_exit_file "${FICHIEROSB}" "Unable to access file  biais (OSB) file ${FICHIEROSB} (give complete path)"    
  if [  "${FICHIERMUSAT}" != "NUL"  ] ; then 
    echo "ERR: Give either -osb either -wsb not the two "
    exit 1   
  fi 
fi 
if [ "${HISTORIK}" != "NUL" ] ; then
  test_exit_file "${HISTORIK}" "Unable to access file historik file ${HISTORIK} (give complete path)"   
fi 
if [ "${METADATA}" != "NUL" ] ; then
  test_exit_file "${METADATA}" "Unable to access metadata file ${METADATA} (give complete path)"   
fi 
if [ "${ANTEX}" != "NUL" ] ; then
  test_exit_file "${ANTEX}" "Unable to access antex file ${ANTEX} (give complete path)"
fi 
if [ "${SINEX}" != "NUL" ] ; then
  test_exit_file "${SINEX}" "Unable to access antex file ${SINEX} (give complete path)"    
fi 
if [ "${MASQUE}" != "NUL" ] ; then
  test_exit_file "${MASQUE}" "Unable to access mask file ${MASQUE} (give complete path)"
fi
if [ "${ORBEX}" != "NUL" ] ; then
  test_exit_file "${ORBEX}" "Unable to access orbex file ${ORBEX} (give complete path)"
fi    
if [ "${P1P2}" != "NUL" ] ; then 
  test_exit_file "${P1P2}" "Unable to access p1p2 file ${P1P2} (give complete path)"
fi

# options dépendant des orbites 
if [ "${type_orb}" != "NUL" ] ; then
  # on plante si f_orb_list non vide 
  if [ "${f_orb_list}" != "" ] ; then 
    echo " Option -orb should give existing SP3 code, either existing SP3 file(s) , not the two."
    exit 1
  fi 
  #
  echo ${KNOWN_SP3_CODE} | grep ${type_orb} >/dev/null
  if [ $? = 0 ] ; then 
    echo " Orbit type: ${type_orb} requested" 
  elif  [ "${repertoire_orb}" != "NUL" ] ; then
    if [ ! -d "${repertoire_orb}" ] ; then
      echo " Directory ${repertoire_orb} for option -repertoire_orb does not exists "
	  exit	 
    fi 
    echo " Orbit type : ${type_orb} ( in ${repertoire_orb} ) requested" 
  else 
    echo " Orbit type: ${type_orb} unknown, please use ${KNOWN_SP3_CODE} instead"
    echo "  ...   or specify -orb XXX -repertoire_orb ..." 
    exit
  fi 
else # type_orb == NUL mais on a demandé des options necessitant les orbites 
  if   [ "${mode_position}" != "NUL" ] ; then 
    echo " WARNING Prairie: option -statique|-mobile ignored since -orb is not present" 
    mode_position='NUL'
  elif [ "${cutoff_elev}"   != "NUL" ] ; then
    echo " WARNING Prairie: option -elevmin... ignored since -orb is not present"
    cutoff_elev='NUL'
  elif [ "${MASQUE}"        != "NUL" ] ; then 
    echo " WARNING Prairie: option -masque ignored since -orb is not present" 
    MASQUE='NUL'
  elif [ "${sec_ecl}"       != "NUL" ] ; then
    echo " WARNING Prairie: option -eclipse / -eclipse_bord ignored since -orb is not present" 
    sec_ecl='NUL' 
  elif [ "${ANTEX}"       != "NUL" ] ; then
    echo " WARNING Prairie: option -antex ignored since -orb is not present" 
    ANTEX='NUL' 
  elif [ "${SINEX}"       != "NUL" ] ; then
    echo " WARNING Prairie: option -sinex ignored since -orb is not present" 
    SINEX='NUL' 
  fi  
fi
# 
if [ "$n" -gt 1 ] ; then 
   out=${out1}_${out2}
elif [ "$n" -eq 0 ] ; then 
   echo " Please give the name of (at least) one existing RINEX file to be processed "
   exit 
else 
   out="${out2}"
fi
\rm "${out}" 2>/dev/null
if [ "${outlis}" != "NUL" ] ; then
 out="${outlis}"
fi 

if [ "${temps_cpu}" -eq 0 ] ; then 
  temps_cpu=$(echo "${n}" | awk '{print $1*15}')
  if [ "${type_orb}" != "NUL" ] ; then
    temps_cpu=$(echo "${n}" | awk '{print $1*30}')
  fi
  if [ "$f_orb_list" != "" ] ; then 
    temps_cpu=$(echo "${n}" | awk '{print $1*30}')
  fi     
fi 
nom_listing="output.prai_${$}.$(i_want_random)"
PBS_QUEU=""
PBS_DIR1="#PBS -l select=1:ncpus=1:mem=${taille_mem}MB"
PBS_DIRM="#PBS -l pvmem=${taille_mem}MB"
nom_shell="$path/v${VERSION_NUMBER}_prairie.${$}.$(i_want_random)"
NRANDOM1="$(i_want_random)"
# echo ${liste_fic}

#Constitution du job LINUX
#************************
cat <<end_job_IBM> "${nom_shell}"
#!/bin/sh
# ressources necessaires pour le job
#-----------------------------------
#PBS -l walltime=${temps_cpu}
${PBS_QUEU}
${PBS_DIR1}
${PBS_DIRM}
#PBS -o $path/${nom_listing}
#PBS -e $path/${nom_listing}.err 

# functions de link ou copie 
#  link ou dezippe si fichier ok 
#  3 arguments :  nom_orig(.gz)  nom_local nom_affichage    
verif_link_file () {
	file_ext=\$1
	file_loc=\$2
	file_typ=\$3
	if [ -s \${file_ext} ] && [ -f \${file_ext} ] ; then 
	  # on accepte les fic zippés 
	  if gunzip -t \${file_ext} 2>/dev/null ; then
	    gunzip -c  \${file_ext} > \${file_loc}
	    echo "\$(ls -l \${file_loc})  ( \${file_ext} )" >> ${path}/${out}
	  else 
        ln -s \${file_ext} \${file_loc}  
        ls -l \${file_loc}  >> ${path}/${out}
      fi 
    else
      echo "ERR: file \${file_typ} \${file_ext} empty or not here"  
      exit 1    
    fi  
}
#  copie si fichier ok 
#  3 arguments :  nom_orig  nom_local nom_affichage    
verif_cp_file () {
	file_ext=\$1
	file_loc=\$2
	file_typ=\$3
	if [ -s \${file_ext} ] && [ -f \${file_ext} ] ; then 
      cp \${file_ext} \${file_loc}  
      chmod +w \${file_loc}
      echo "\$(ls -l \${file_loc})  ( \${file_ext} )" >> ${path}/${out} 
    else
      echo "ERR: file \${file_typ} \${file_ext} empty or not here"   
      exit 1    
    fi  
}


echo " Prog is ${PRAIRIELNX} ( ${VERSION} on \$(uname -s) )"
# attention TMPDIR est une variable HAL (ici on la redefini localement)
# pas de export donc 
if [ ! -z \${GS_TMP} ]  ; then 
  TMPDIR=\${GS_TMP}/PRAIRIE_\${\$}_\${LOGNAME}_${NRANDOM1} # ATTENTION pas de \$ pour NRANDOM1
else 
  if [ -z \${TMPDIR} ] ; then 
    TMPDIR=/tmp/PRAIRIE_\${\$}_\${LOGNAME}_${NRANDOM1}  
  else 
    TMPDIR=\${TMPDIR}/PRAIRIE_\${\$}_\${LOGNAME}_${NRANDOM1}
  fi
fi  
cd ${path_init}
mkdir \${TMPDIR} 2>/dev/null
cd \${TMPDIR} || exit 

  echo "OUTPUT EXE_PRAIRIE" > ${path}/${out}
  echo "******************" >> ${path}/${out}
  echo "Commande $0 ${commande}" >> ${path}/${out}

\rm liste_ent PRAIRIE.dat SORTIE_MUSAT  2>/dev/null 
for i in ${liste_fic} ; do 
  ln -s \$i . 
  ${DECOMP_HATANAKA} -f \$(basename \$i) | tee -a ${path}/${out} 
done 
# 
# Application des biais P1C1 
# 
if [ "${P1P2}" != "NUL" ] ; then
  verif_link_file ${P1P2} p1p2.dat p1p2
  if [ ${VERSION_NUMBER} -eq  0 ] ; then 
    echo " Warning: Version de dev. - cc2noncc (p1p2/p1c1) correction made by prairie if necessary"
  elif [ ${VERSION_NUMBER} -lt 40 ] ; then 
    for i in *.??o ; do
      ${CC2NONCC} \$i \${i}_out p1p2.dat  | grep -v  "CC2nonCC ESOC Version" | awk '{if (length(\$1) > 0 ) print \$0}' >  outcc.dat_sta_courante
      if [ -s outcc.dat_sta_courante ] ; then 
	    \rm outcc.dat_sta_courante
        if [ -s \${i}_out ] ; then 
	      echo \$i " correction cc2noncc appliquee " >> ${path}/${out} 
	      mv \${i}_out \${i}
        else
	      echo  \$i " correction cc2noncc non appliquee = probleme "  >> ${path}/${out} 
        fi
      fi 
    done
  else
    echo " cc2noncc (p1p2/p1c1) correction made by prairie if necessary"
  fi  
else
  echo " No p1p2 (p1p2/p1c1) file given"
fi
  # deux types possibles *.??o et *.rnx
  ls -1 *.??o *.??O 2>/dev/null >  liste_totale.o 
  ls -1 *_??.rnx *_??.RNX 2>/dev/null > liste_totale.rnx
  comment_aff=""
  for i in .o .rnx ; do
    nb=\$(wc -l liste_totale\${i} | awk '{print \$1}')
    if [ \$nb -gt 0 ] ; then 
      comment_aff="\${comment_aff} \$nb file(s) with \${i} extension"
    fi 
  done 
  cat liste_totale.o liste_totale.rnx > liste_totale
  awk '{a=substr(\$1,1,4) ; print "grep "a" liste_totale > "a".liste"}'  liste_totale  | sort | uniq > exec.prairie
  chmod +x exec.prairie
  . ./exec.prairie
  nbstations_a_traiter=\$(ls -1 ????.liste | wc -l)
  if [ \${nbstations_a_traiter} -eq 0 ] ; then 
    echo " Please give the name of (at least) one EXISTING RINEX file to be processed "
    exit 
  else 
    if [ ${force_unique} -eq 0 ] || [ \${nbstations_a_traiter} -eq 1 ] ; then 
      echo " \${nbstations_a_traiter} station(s) to be processed: \$(ls ????.liste | awk -F. '{print \$1}') : \${comment_aff}"
    else   
      echo " WAR: option force_unique active, on supprime \$(ls ????.liste | \tail -n +2 | awk -F. '{print \$1}')"
      \rm \$(ls ????.liste | \tail -n +2)      
      nbstations_a_traiter=\$(ls -1 ????.liste | wc -l)
      echo " \${nbstations_a_traiter} station(s) to be processed:  \$(ls ????.liste | awk -F. '{print \$1}')"       
    fi 
  fi 
  # fichier selection avec modifications eventuelles
  ls -l ${SELECTION_OBS}
  if [ -s ${SELECTION_OBS}  ] ; then
    if [ ${MODIF_SELECTION:-0} -eq 1 ]  ; then 
      verif_cp_file ${SELECTION_OBS} selection_observables.dat selection
      if [ "${CONS_IGNORE:-NUL}" != "NUL" ] ; then
        echo " On ignore la(les) constellations "${CONS_IGNORE}  >> ${path}/${out}
        echo " On ignore la(les) constellations "${CONS_IGNORE}  
        for i in ${liste_cons_ignorees} ; do
          sed "s/^  \${i}/# \${i}/g" selection_observables.dat >  \${TMPDIR}/temporaire
	      mv \${TMPDIR}/temporaire selection_observables.dat
        done
        # cat selection_observables.dat | grep -v "^#"
      fi
      if [ "${FREQUENCES:-NUL}" != "NUL"  ] ; then 
        echo " On  garde les frequences "${FREQUENCES}  >> ${path}/${out}
        echo " On  garde les frequences "${FREQUENCES}  
        awk '/^  . RNX2/{freq=substr(\$0,69,1)*10+substr(\$0,77,1) ; if ( freq == '${FREQUENCES}' ) print \$0,freq}' selection_observables.dat  > \${TMPDIR}/temporaire
        awk '/^  . RNX3/{freq=substr(\$0,68,1)*10+substr(\$0,76,1) ; if ( freq == '${FREQUENCES}' ) print \$0,freq}' selection_observables.dat  >> \${TMPDIR}/temporaire
	    mv \${TMPDIR}/temporaire selection_observables.dat 
      fi 
      # cat selection_observables.dat 
    else
      verif_link_file ${SELECTION_OBS} selection_observables.dat selection
    fi   
  else 
    echo "apres la version v40 le fichier ${SELECTION_OBS} est recquis " 
  fi 
  if [ "${FICHIERMUSAT}" != "NUL" ] ; then
    verif_link_file ${FICHIERMUSAT} MuSatRef.res.dat musat 
    if [ "${P1P2}" = "NUL" ] ; then
      echo "Prairie: Attention option -wsb presente mais pas -cc2noncc: blocage G12 impossible sur les stations concernees" 
    fi   
  fi 
  if [ "${FICHIEROSB}" != "NUL" ] ; then
    verif_link_file ${FICHIEROSB} OSB_bias.dat osb    
  fi 
  if [ "${HISTORIK}" != "NUL" ] ; then
    verif_link_file ${HISTORIK} historik_glonass historik        
  fi
  if [ "${METADATA}" != "NUL" ] ; then
    verif_link_file ${METADATA} gnss_metadata.snx metadata       
  fi
  if [ "${ANTEX}" != "NUL" ] ; then
    verif_link_file ${ANTEX} antex_prairie.atx antex   
  fi  
  if [ "${SINEX}" != "NUL" ] ; then
    verif_link_file ${SINEX} sinex_prairie.snx  sinex          
  fi  
  if [ "${ORBEX}" != "NUL" ] ; then
    # faudra faire la concatenation à l'extérieur ?!?
    verif_link_file ${ORBEX} orbex.obx orbex  
  fi 
  # masque (format type shom)
  if [ "${MASQUE}" != "NUL" ] ; then
    if [ \${nbstations_a_traiter} -gt  1  ] ; then
      echo " WAR:option masque annulee : si fic. masque present alors seule une station peut etre traitee a la fois"
    else 
      verif_link_file ${MASQUE} masque.dat masque   
    fi
  fi 
  # 
  if [ "${fichier_option}" != "NUL" ] ; then
    verif_cp_file ${fichier_option} options_prairie.dat option    
  fi
  # attitude (format type shom) 
  if [ "${ATTITUDE}" != "NUL" ] ; then
    if [ \${nbstations_a_traiter} -gt  1  ] ; then
      echo " WAR:option attitude annulee : si fic. attitude present alors seule une station peut etre traitee a la fois"
    else
      verif_link_file ${ATTITUDE} attitude.dat attitude 
      if [ -s ${SAUTS_DE_TUCS} ]  ; then 
        if [ ! -h liste_sauts_tucs_1s.dat ] ; then 
          ln -s  ${SAUTS_DE_TUCS} liste_sauts_tucs_1s.dat
        fi
        ls -l liste_sauts_tucs_1s.dat >> ${path}/${out}
      else 
        echo " ERR: fichier saut de tuc absent , on peut pas traiter attitude "
        exit 1 
      fi 
    fi 
  fi 
  # modifications fichier options  
  # cas ou on fait passer des options ligne de commande dans le fichier options 
  if [   ${mode_position} != "NUL" ] ; then
    echo ${mode_position}" "1.00 >> options_prairie.dat 
  fi 
  if [ "${cutoff_elev}" != "NUL" ] ; then
    echo "ELEVMIN   ${cutoff_elev}" >> options_prairie.dat 
    echo "GARDE_ELEV_UNK ${garde_elev}" >> options_prairie.dat
  fi
  if [ "${sec_ecl}" != "NUL" ] ; then
    echo "ECLIPSE  ${sec_ecl}" >> options_prairie.dat 
    if [ "${ECLBORD}" != "NUL" ] ; then
      echo "SUPECL0H 1" >> options_prairie.dat 
    fi 
  fi
  if [ "${posit_demande}" != "NUL" ] ; then
    echo "POSITIONNEMENT  ${posit_demande}" >> options_prairie.dat 
  fi
  echo "ACQ_ONLY "${ACQ_ONLY} >> options_prairie.dat
  echo "DEBUG_WL "${debug_wl} >> options_prairie.dat
  if [ "$debugtout" = "1" ] ; then 
    echo "DEBUG   150" >> options_prairie.dat
  fi 
  #
  \rm \${TMPDIR}/SORTIE_PDGR90_TOTAL 2>/dev/null
  for i in ????.liste ; do
    \rm sortiePDGR90 Suivi_musat.sparse residus_wl.dat hwl_rec.dat \${TMPDIR}/fichier_des_sp3.lst 2>/dev/null
    echo \$i  > \${TMPDIR}/ent.prai
    echo $pas >> \${TMPDIR}/ent.prai
    # cat \${TMPDIR}/ent.prai
    echo " On traite: " >> ${path}/${out} 
    awk '{printf("   %s\n",\$1) }' \$i  >> ${path}/${out}
 
    if [ ${type_orb} != "NUL" ] ; then
      type_orb=${type_orb}
      repertoire_orb=${repertoire_orb}
      # premier passage ou on cherche les dates pour attacher les fic sp3
      echo "parcours_only" > \${TMPDIR}/parcours_only
      ${PRAIRIELNX} < \${TMPDIR}/ent.prai >> \${TMPDIR}/output_initial_parcours 
      ligne_ap_parc=\$(grep "FIN_APRES_PARCOURS:" \${TMPDIR}/output_initial_parcours)
      if [ "\${ligne_ap_parc:-PROBLEME}" = "PROBLEME" ] ; then 
        cat output_initial_parcours >> ${path}/${out} 
        grep ERR output_initial_parcours  >> ${path}/${out} 
        echo " ERR: Unable to process  file(s) to  detect processing dates" >> ${path}/${out}
        echo " ERR: Unable to process  file(s) to  detect processing dates" 
        exit 
      fi  
      
      deb_sp3=\$(echo \${ligne_ap_parc} | awk '{print \$2-1}')
      fin_sp3=\$(echo \${ligne_ap_parc} | awk '{print \$3+1}')
      nb_sp3_attendus=\$(echo \${fin_sp3} \${deb_sp3} | awk '{print \$1-\$2+1}') 
      d_sp3=\${deb_sp3}
      while [ \${d_sp3} -le \${fin_sp3} ] ; do        
        WWWD=\$(jjul \$d_sp3  | grep GPS | awk '{printf("%4.4d%1.1d",\$3,\$4)}')
	    if [ \${type_orb} = "GRM" ] ; then 
	      if [ \${d_sp3} -le 23841  ] ; then # 12/04/2015 : debut grm
	        echo "no correct grm orbits before 12/04/2015; we change to grg"
	        type_orb="GRG"
  	      fi
	    fi 
	    petit_type_orb=\$(echo \${type_orb} | tr '[:upper:]' '[:lower:]') 
	    # 
	    # Pour les traitements CA qui sont finalisés de manière hebdomadaire, 
	    # mais traités de manière diurne, on a besoin d’avoir accès (prétraitements ,  biais iono ,...)
	    #  aux fichiers quasi-finaux de la veille avant qu’ils soient validés définitivement et archivés 
	    # sous les noms officiels GRM/GRG (opération qui n’est faite qu’après validation). 
	    # D’où ce répertoire DIRSP3_ALTER dans les cas GRG / GRM 
	    # « spécifique CA » qui ne nécessite pas d’etre mis sous MIROIR_STAF. 
	    #
	    case \${type_orb} in 
	    G20) # G20 puis GRG 
	        # Demarrage g20(300s) au 03/05/2000   
	        #       fin g20       le 14/01/2023
	        DIRSP3=${ROOT_SP3}/gin/batch/orbite/G20  ; fic_sp3=g20\${WWWD}.sp3.Ci3G20
	        DIRSP3_ALTER=${ROOT_SP3}/igs             ; fic_sp3_alter=grg\${WWWD}.sp3
	    ;;
	    GRG|MG3) # MG3 puis GRG puis hebdo_predites
	      if [ \${d_sp3} -le 26627 ] ; then        # 26/11/2022 = fin des mg3 
	        DIRSP3=${ROOT_SP3}/re3                 ; fic_sp3=mg3\${WWWD}.sp3.Ci9PAU  
	        # Demarrage mg3(300s)   au 03/05/2000   
	        # pas de glonass mg3 avant 04/11/2008 
	        # pas de galileo mg3 avant 31/12/2016 
	        DIRSP3_ALTER=${ROOT_SP3}/igs           ; fic_sp3_alter=grg\${WWWD}.sp3    
	        # Demarrage grg(900s)   au 29/11/2009 
	        # pas de glonass grg avant 09/01/2011 
	        #           grg(300s)   au 24/01/2021 
	        # pas de Galileo grg avant 27/11/2022
	      else  # apres  on prend grg ou les hebdo predites pour les dates les plus récentes
	        DIRSP3=${ROOT_SP3}/igs                 ; fic_sp3=grg\${WWWD}.sp3
	        DIRSP3_ALTER=${ROOT_SP3_LOC}/HEBDO_SP3 ; fic_sp3_alter=heb\${WWWD}.sp3
	      fi
    	    ;; 
         GRM) # grm si dispo , sinon mg3
            DIRSP3=${ROOT_SP3}/mgx       ;  fic_sp3=grm\${WWWD}.sp3
            # contient Galileo après 04/2015
            # contient Beidou après  11/2024
            DIRSP3_ALTER=${ROOT_SP3}/re3 ;  fic_sp3_alter=mg3\${WWWD}.sp3.Ci9PAU  
            ;;
	   	*)    
	        DIRSP3=\${repertoire_orb}  ;  fic_sp3=\${petit_type_orb}\${WWWD}.sp3
	        DIRSP3_ALTER=\${DIRSP3}    ;  fic_sp3_alter=\${fic_sp3}
	    ;;    
	    esac 
	    # recherche (successive) des fichiers sp3 
	    ok_sp3=0
	    for fic_sp3_tst in \${DIRSP3}/\${fic_sp3}    \
	                       \${DIRSP3}/\${fic_sp3}.gz \
	                       \${DIRSP3}/\${fic_sp3}.Z  \
	                       \${DIRSP3_ALTER}/\${fic_sp3_alter}    \
	                       \${DIRSP3_ALTER}/\${fic_sp3_alter}.gz \
	                       \${DIRSP3_ALTER}/\${fic_sp3_alter}.Z     ; do
	      nomsp3_retenu=\$(basename \${fic_sp3_tst})
          nomsp3_retenu=\${nomsp3_retenu%%.gz}
          nomsp3_retenu=\${nomsp3_retenu%%.Z}
	      if [ -s \${fic_sp3_tst} ] ; then 
	        zcat -t \${fic_sp3_tst} 2>/dev/null 
	        if [ \$? -eq 1 ] ; then 
	          cat \${fic_sp3_tst}  > \${TMPDIR}/\${nomsp3_retenu}
	        else 
	          zcat \${fic_sp3_tst} > \${TMPDIR}/\${nomsp3_retenu}
	        fi 
	        if [ -s \${TMPDIR}/\${fic_retenu} ] ; then
	          echo \${nomsp3_retenu} >> \${TMPDIR}/fichier_des_sp3.lst 
	          ok_sp3=1
	          break    # sort de la boucle for 
	        fi 
	      fi 
	    done   
	    # fin de la recherche sp3
	    if [ \${ok_sp3} -eq 0 ] ; then 
	      echo " pas de fic  \${DIRSP3}/\${fic_sp3} ni \${DIRSP3}/\${fic_sp3_alter}" 
	      \rm \${TMPDIR}/fichier_des_sp3.lst 2>/dev/null
	    fi 
	    d_sp3=\$(echo \${d_sp3} | awk '{print \$1 + 1}')
      done
      #      
      nb_sp3_presents=\$( ( wc -l \${TMPDIR}/fichier_des_sp3.lst 2>/dev/null || echo 0 ) | awk '{print \$1}' )
      if [ \${nb_sp3_presents} -gt 0 ] ; then         
 
        if [ \${nb_sp3_presents} -lt \${nb_sp3_attendus} ] ; then    
          echo "WAR: some sp3 file(s) are missing (using GARDE_ELEV_UNKNOWN option will keep anyway the measurements)"
        fi
      else 
	      \rm \${TMPDIR}/fichier_des_sp3.lst 2>/dev/null        
      fi         
      \rm \${TMPDIR}/parcours_only
    fi
    # cas ou l'utilisateur fournit les orbites sp3 nommément 
    if [ "${f_orb_list}" != "" ] ; then 
      for fic_sp3_tst in ${f_orb_list} ; do 
        nomsp3_retenu=\$(basename \${fic_sp3_tst})
        nomsp3_retenu=\${nomsp3_retenu%%.gz}
        nomsp3_retenu=\${nomsp3_retenu%%.Z}
        zcat -t \${fic_sp3_tst} 2>/dev/null 
	    if [ \$? -eq 1 ] ; then 
	      cat \${fic_sp3_tst}  > \${TMPDIR}/\${nomsp3_retenu}
	    else 
	      zcat \${fic_sp3_tst} > \${TMPDIR}/\${nomsp3_retenu}
	    fi 
        echo \${nomsp3_retenu} >> \${TMPDIR}/fichier_des_sp3.lst
      done 
    fi  
    if [ -s \${TMPDIR}/fichier_des_sp3.lst  ] ; then 
      awk -F/ '{print " attache sp3: "\$NF}' \${TMPDIR}/fichier_des_sp3.lst >> ${path}/${out}
      awk -F/ '{print " attache sp3: "\$NF}' \${TMPDIR}/fichier_des_sp3.lst
      if [ -s ${SAUTS_DE_TUCS} ]  ; then
        if [ ! -h liste_sauts_tucs_1s.dat ] ; then 
          ln -s  ${SAUTS_DE_TUCS} liste_sauts_tucs_1s.dat
        fi 
  	    ls -l liste_sauts_tucs_1s.dat >> ${path}/${out}
      else
        echo " ERR: fichier saut de tuc absent , on peut pas traiter attitude "
	    exit 1  
      fi
    fi 
    #
    # On lance enfin prairie
    # 
    ${PRAIRIELNX} < \${TMPDIR}/ent.prai >> ${path}/${out} 
    if [ ${DO_NOT_OUTPDGR} -eq 1 ] ; then 
       \rm sortiePDGR90 
    fi 
    if [ -s sortiePDGR90 ] ; then  
     cat sortiePDGR90 >> \${TMPDIR}/SORTIE_PDGR90_TOTAL
     taille_s=\$(ls -l  sortiePDGR90 | awk '{print \$5}')
    else 
     taille_s=0
    fi  
    liste_o=\$(cat \$i)
    nombre_o=\$(ls -1 \${liste_o} | wc -l )
    taille_o=\$(ls -lL  \${liste_o} | awk '{s=s+\$5 }END{print s}')
    echo "\${i} ( \${nombre_o} \${taille_o} ) sortiePDGR90 ( \${taille_s} )" >> ${path}/${out} 
    [ -s Suivi_musat.sparse ] && cat Suivi_musat.sparse  >> SORTIE_MUSAT 
    [ -s residus_wl.dat ] && cat residus_wl.dat >> RESIDUS_WL.dat 
    [ -s hwl_rec.dat ] && cat hwl_rec.dat >> HWL_REC.dat
    [ -s sortie_biaismoyens_wl_p1c1.dat ] && cat sortie_biaismoyens_wl_p1c1.dat  >> BIAISMOYENS_WL_P1C1.dat 
  done
  # tri fichier de mesure ici :
  if [ ${SORT} -eq 1 ] ; then
    echo "Trie du fichier de mesures"
    if [ -s \${TMPDIR}/SORTIE_PDGR90_TOTAL ] ; then 
      sort -k 1.6,1.10 -k 1.12,1.17 \${TMPDIR}/SORTIE_PDGR90_TOTAL -o \${TMPDIR}/SORTIE_PDGR90_TOTAL_TRIE
      mv \${TMPDIR}/SORTIE_PDGR90_TOTAL_TRIE \${TMPDIR}/SORTIE_PDGR90_TOTAL
    fi 
  fi
  # recuperation de la sortie musat eventuellement renommee 
  if [ "${outmusat}" != "NONE" ] ; then 
    outfich=SORTIE_MUSAT
    [ -s \${outfich} ] && mv \${outfich} ${path}/${outmusat}
  fi   
  # recuperation de la sortie p1c1 eventuellement renommee 
  if [ "${outp1c1}" != "NONE" ] ; then 
    outfich=BIAISMOYENS_WL_P1C1.dat
    [ -s \${outfich} ] && mv \${outfich} ${path}/${outp1c1}
  fi 
  # recuperation de la sortie speciale eventuellement renommee
  if [ "${outspeciale}" != "NONE" ] ; then 
    outfich=SPECIALE.dat
    [ -s \${outfich} ] && mv \${outfich} ${path}/${outspeciale}
  fi 
  # recuperation des autres sorties non usuelles 
  for outfich in HWL_REC.dat RESIDUS_WL.dat ; do 
     [ -s \${outfich} ] && mv \${outfich} ${path}/\${outfich}
  done
  # recuperation des mesures
  if  [ -s \${TMPDIR}/SORTIE_PDGR90_TOTAL ] ; then 
    mv \${TMPDIR}/SORTIE_PDGR90_TOTAL ${path}/${outPDG}
  fi 
  if [ $debugtout -eq 1 ] ; then
    \rm -r ${path}/DEBUGPRAI 2>/dev/null 
    mkdir ${path}/DEBUGPRAI
    if [ -d ${path}/DEBUGPRAI ] ; then 
      cp -r -p \${TMPDIR}/* ${path}/DEBUGPRAI
      echo "copie de debug sous "${path}/DEBUGPRAI
    else
      echo "impossible de copier repertoire de travail ?"
    fi 
  fi 
  cd /tmp
  \rm -r \${TMPDIR}

end_job_IBM
cd "${path}" || exit 

chmod +x "${nom_shell}" 
 

if [ $QS -gt 0 ] ; then
  numjob=$($QSUB "${nom_shell}")
  echo "waiting end of job...: $numjob"
  /work/GRGS/users/loyer/PRAIRIE/wait_hal "$numjob" -f 10 
  grep BILAN "${path}/${out}" | grep -v ligne
  \rm -r  "${nom_shell}" 
else 
  ${nom_shell} 
  # echo "${nom_shell}"
  \rm -r  "${nom_shell}"
  grep BILAN "${path}/${out}" | grep -v ligne
fi 
