#!/bin/bash
set -e

YEAR_START=$1
YEAR_END=$2

DOY_START=$3
DOY_END=$4

STATION=$5

PROJECT=$6

for YEAR in $(seq $YEAR_START $YEAR_END)
do

    for DOY in $(seq $DOY_START $DOY_END)
    do

        timeout --foreground 10m ./Test_SHOM $YEAR $DOY $STATION $PROJECT

    done

done
